# This is a basic workflow to help you get started with Actions

name: TestingCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Project1 branch
  push:
    branches: [ Project1 ]
  pull_request:
    branches: [ Project1 ]
  workflow_dispatch:
    inputs:
     name:
      description: "Reason for Build"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 1 Building project
        run: mvn clean install
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
